#!/bin/sh
#
# Perform necessary packageiq setup steps
# after package is installed.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

if ! getent passwd packageiq > /dev/null; then
  echo "Adding packageiq user"
  useradd -c "PackageIQ User" -d /home/packageiq -m -U -s "/sbin/nologin" packageiq
fi

chown -R root:root /etc/packageiq
chmod 0755 /etc/packageiq
chmod 0644 /etc/packageiq/*

if [ -b '/usr/bin/systemctl' ]
then
  echo "Reloading systemctl daemon"
  /usr/bin/systemctl daemon-reload
fi

echo "Thank you for installing packageiq!"

exit 0
